services:

  server:
    build: server-alysia
    restart: unless-stopped
    volumes:
      - music:/music
    ports:
      - 8081:8080

  webapp:
    build: webapp
    restart: unless-stopped
    ports:
      - 8080:80

volumes:
  music:
